### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by andrewsuzuki** [andrewsuzuki/otep#1]
Need a demo site showcasing all components.

http://andrewsuzuki.com/otep

## Todo

- [x] gh-pages and deployment
- [x] Router
- [ ] Structure and style
- [ ] Installation and setup page
- [ ] Component showcase (see below)

#### Basic

- [ ] A
- [ ] H1-H6
- [ ] Image
- [ ] List, ListItem
- [ ] SpanBlock
- [ ] Icon

#### Layout

- [ ] Section
- [ ] Container, Column, Row
- [ ] Media, Level (AtLeft, AtCenter, AtRight)
- [ ] Stickler

#### Form

- [ ] Button, ButtonGroup, ButtonLink, ButtonOutlined
- [ ] Field, FieldHelp, FieldFeedback, FieldFeedbackSet
- [ ] Control, ControlSpinner
- [ ] Input, TextInput, DateInput, EmailInput, NumberInput, PasswordInput, TelInput
- [ ] Checkable, CheckableSet (Radio, Checkbox)
- [ ] Textarea
- [ ] Select
- [ ] Label

#### Components

- [ ] Navbar
- [ ] Hero, HeroTitle, HeroSubtitle
- [ ] Modal, ModalContent
- [ ] Alert
- [ ] Badge
- [ ] Close
- [ ] Tile, Box
- [ ] Tabs, Tab
- [ ] Pagination
